apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
configMapGenerator:
  - name: alloy-config
    files:
      - config.alloy
    options:
      disableNameSuffixHash: true
resources:
  - repository.yaml
  - release.yaml