apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  releaseName: alloy
  targetNamespace: grafana
  interval: 5m
  chart:
    spec:
      chart: alloy
      version: '0.10.1'
      sourceRef:
        kind: HelmRepository
        name: alloy
      interval: 5m
  values:
    controller:
      type: 'deployment'
    alloy:
      extraPorts:
        - name: "otlp-grpc"
          port: 4317
          targetPort: 4317
          protocol: "TCP"
        - name: "otlp-http"
          port: 4318
          targetPort: 4318
          protocol: "TCP"
      configMap:
        create: false
        name: alloy-config
        key: config.alloy