apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  releaseName: loki-deployment
  targetNamespace: grafana
  interval: 15m
  chart:
    spec:
      version: "6.x"
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 24h
  values:
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    test:
      enabled: false
    loki:
      auth_enabled: false
      limits_config:
        allow_structured_metadata: true
        retention_period: 24h
        volume_enabled: true
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage_config:
        aws:
          region: us-west-2
      pattern_ingester:
        enabled: true
      ruler:
        enable_api: true
      extraMemberlistConfig:
        bind_addr:
          - "${MY_POD_IP}"
      storage:
        type: s3
        bucketNames:
            chunks: "${LOKI-S3-CHUNK-BUCKET}"
            ruler: "${LOKI-S3-RULER-BUCKET}"
        s3:
          # AWS region where the S3 bucket is located
          region: us-west-2
          # AWS secret access key
          secretAccessKey: "${LOKI-S3-SECRETACCESSKEY}"
          # AWS access key ID
          accessKeyId: "${LOKI-S3-ACCESKEYID}"
          # AWS signature version (e.g., v2 or v4)
          signatureVersion: v4
          # Forces the path style for S3 (true/false)
          s3ForcePathStyle: false
          # Allows insecure (HTTP) connections (true/false)
          insecure: false
    minio:
      enabled: false
    lokiCanary:
      enabled: false
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      extraArgs:
        - -config.expand-env=true
      extraEnv:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: LOKI-S3-CHUNK-BUCKET 
          valueFrom:
            secretKeyRef:
              name: loki-secrets
              key: loki_chunk_bucket
        - name: LOKI-S3-RULER-BUCKET 
          valueFrom:
            secretKeyRef:
              name: loki-secrets
              key: loki_ruler_bucket
        - name: LOKI-S3-ACCESKEYID 
          valueFrom:
            secretKeyRef:
              name: awssm-secret
              key: access-key
              namespace: default
        - name: LOKI-S3-SECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: awssm-secret
              key: secret-access-key
              namespace: default
    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0