apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-secrets
spec:
  refreshInterval: "0h"
  secretStoreRef:
    name: aws-paramstore
    kind: ClusterSecretStore
  data:
  - secretKey: loki_chunk_bucket
    remoteRef:
      key: lab_loki_config
      property: chunk_bucket
  - secretKey: loki_ruler_bucket
    remoteRef:
      key: lab_loki_config
      property: ruler_bucket
  - secretKey: loki_admin_bucket
    remoteRef:
      key: lab_loki_config
      property: admin_bucket