apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 15m
  url: oci://ghcr.io/grafana/kustomize/grafana-operator
  ref:
    tag: v5.17.1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: grafana
  images:
    - name: ghcr.io/grafana/grafana-operator
      newTag: v5.17.1
  prune: true
  sourceRef:
    kind: OCIRepository
    name: grafana-operator
  path: ./overlays/namespace_scoped