apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./overlays/namespace_scoped