apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  force: false
  dependsOn:
    - name: grafana
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: loki-deployment
      namespace: grafana
  interval: 10m0s
  targetNamespace: grafana
  path: ./apps/lab1/loki
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system